### ISSUE TITLE
代码高亮功能不能正常使用

### ISSUE THREAD

**Issue by Hellowor1d** [Kaijun/hexo-theme-huxblog#25]
Hexo 的代码高亮依赖于 highlight.js 实现，一般在根目录的配置中 
```yaml
    highlight:
        enable: true
        line_number: true
        auto_detect: false
        ab_replace:
```
如上设置即可实现代码高亮,但是我原来使用的[ yilia 主题](https://github.com/litten/hexo-theme-yilia)在切换主题到 hexo-theme-huxblog 之后，代码高亮部分失效了，真的很喜欢原来的代码高亮颜色配置。
查看过  Hux 的 Jekyll 主题原来的高亮方案换成了 Ruby 的 rouge，跟 hexo 实现方案不一样。
新主题下，即便开启了 **highlight  enable:  true** ，还是没能让 highlight.js 执行，所以代码高亮失败。
奇怪的是，开启 **auto_detect:  true** 之后，使用在```之间的代码能高亮，但是四空格缩进写的代码行，却无法高亮，目前正在困惑中，怎样才能在不大动配置的情况下，让代码能够通过 hexo 原有方案正常高亮呢， 希望得到帮助，谢谢.这是我的博客地址,描述了我的问题:  [color highlight test](http://hellowor1d.github.io/2016/07/27/color/)
