### ISSUE TITLE
Which markdown renderer  engine did you use??

### ISSUE THREAD

**Issue by YenYuHsuan** [Kaijun/hexo-theme-huxblog#55]
as title, I'm wondering **which markdown engine** and **how to change it**.
sorry, I'm new at hexo plugins.

**Comment by Kaijun** [comment]
@YenYuHsuan  sorry for myy late reply. 
It's using [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) which is also labeled here in the [package.json](https://github.com/Kaijun/hexo-theme-huxblog/blob/master/package.json#L16)

**Comment by Kaijun** [comment]
@YenYuHsuan if u gonna change the it, u have to check if the renderer engine u want has hexo support. 

take [hexo-renderer-markdown-it](https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/Getting-Started) as an example:  basically just follow the instruction of the plugins u wanna install.

**Comment by YenYuHsuan** [comment]
@Kaijun thanks for your reply 😄 
I've tried install hexo-renderer-markdown-it
but the header anchor didn't render when i change the `icon: #` into another icon
so i found out that in `layout/post.ejs` there are some codes cause this:
```js
async("https://cdn.bootcss.com/anchor-js/1.1.1/anchor.min.js",function(){
        anchors.options = {
          visible: 'hover',
          placement: 'left',
          icon: # // this is the header anchor "unicode" icon
        };
```
i have to change icon from here.

if it is possible that don't need to change from `layout/post.ejs`, but just follow the [hexo-renderer-markdown-it](https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/Getting-Started) instruction that edit the `_config.yml`:
```yml
markdown:
  anchors:
    level: 2
    collisionSuffix: 'v'           
    permalink: false              
    permalinkClass: header-anchor 
    permalinkSymbol: ¶    #change icon here
```

thanks again 😆
