### ISSUE TITLE
作者好，请问代码块行号可以设置为不显示吗？

### ISSUE THREAD

**Issue by MarshallMathersIII** [Kaijun/hexo-theme-huxblog#60]
RT

**Comment by zihengcat** [comment]
修改`_config.yml`配置文件中的  highlight 选项即可。
```
...
highlight:
  enable: true
  line_number: true    #修改这里 true --> false
  auto_detect: true
  tab_replace:
...
```
